package:
  name: ngsi_pm_sh
  version: 2.2.0rc1

about:
  home: https://github.com/BCM-HGSC/nsgi-pm
  license: MIT
  summary: ngsi-pm bash scripts package

source:
  path: ..

build:
  noarch: generic
  script: cp bin/* "$PREFIX"/bin/

requirements:
  build:
    - bash
    - coreutils
  run:
    - bash
    - coreutils
    - ngsi_pm_py