{% set data = load_setup_py_data() %}

package:
  name: ngsi_pm_py
  version: {{ data['version'] }}

about:
  home: https://github.com/BCM-HGSC/ngsi-pm
  license: MIT
  summary: {{ data['description']}}

source:
  path: ..

build:
  noarch: python
  skip: True  # [py<36]
  script: >-
    python setup.py install
    --single-version-externally-managed
    --record=record.txt

requirements:
  # Dependencies are defined in setup.py
  build:
    - python>=3.6,<4
    - setuptools
    {% for dep in data['setup_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
  run:
    - python>=3.6,<4
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest
