{% set data = load_setup_py_data() %}

package:
  name: ngsi_pm
  version: {{ data['version'] }}

about:
  home: https://github.com/BCM-HGSC/ngsi-pm
  license: MIT
  summary: ngsi-pm scripts package

source:
  path: ..

build:
  noarch: generic

requirements:
  build:
    - python>=3.6,<4
    - setuptools
    {% for dep in data['setup_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    - bash
    - coreutils
  run:
    - python>=3.6,<4
    {% for dep in data['install_requires'] %}
    - {{ dep.lower() }}
    {% endfor %}
    - bash
    - coreutils
    - samtools

test:
  source_files:
    - tests
  requires:
    - pytest
  commands:
    - pytest
